// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://driiuzbscrtzxbykbjem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyaWl1emJzY3J0enhieWtiamVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjE3NTcsImV4cCI6MjA3MTY5Nzc1N30.4O_2zkEztMuJa_VBPHkIiOI0PrcjNhaWOlf13ARI41c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});